steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_URL=$_VITE_API_URL'
      - '-t'
      - '$_IMAGE_NAME'
      - '.'
images:
  - '$_IMAGE_NAME'
substitutions:
  _VITE_API_URL: 'https://server-204524688402.asia-northeast1.run.app'
  _IMAGE_NAME: 'gcr.io/gemini-hack-485913/coach-creator/frontend:latest'
